In [1]:
import json
from pathlib import Path

import pandas as pd

In [3]:
from google.colab import files

uploaded = files.upload()

Saving 2026-05-27_17-16-02.json to 2026-05-27_17-16-02.json

Raw JSON data from Open-Meteo API was loaded for normalization.

In [4]:
raw_path = "/content/2026-05-27_17-16-02.json"

with open(raw_path, "r", encoding="utf-8") as file:
    data = json.load(file)

print(type(data))
print(data.keys())

<class 'dict'>
dict_keys(['latitude', 'longitude', 'generationtime_ms', 'utc_offset_seconds', 'timezone', 'timezone_abbreviation', 'elevation', 'hourly_units', 'hourly'])

One row in the normalized dataset represents one hour of weather observations in Tokyo.

In [5]:
hourly = data["hourly"]

df = pd.DataFrame({
    "ts": hourly["time"],
    "temperature_2m": hourly["temperature_2m"],
    "relative_humidity_2m": hourly["relative_humidity_2m"],
    "precipitation": hourly["precipitation"],
    "wind_speed_10m": hourly["wind_speed_10m"],
    "city_id": "JP_TYO",
})

The initial DataFrame structure was inspected using head(), shape and dtypes.

In [6]:
df.head()

,ts,temperature_2m,relative_humidity_2m,precipitation,wind_speed_10m,city_id
0,2024-05-01T00:00,19.6,93,0.0,1.6,JP_TYO
1,2024-05-01T01:00,19.9,90,0.0,1.3,JP_TYO
2,2024-05-01T02:00,19.2,94,0.0,2.5,JP_TYO
3,2024-05-01T03:00,18.9,97,0.0,3.3,JP_TYO
4,2024-05-01T04:00,19.1,92,0.0,7.4,JP_TYO

In [7]:
df.shape

(168, 6)

In [8]:
df.dtypes

ts                       object
temperature_2m          float64
relative_humidity_2m      int64
precipitation           float64
wind_speed_10m          float64
city_id                  object
dtype: object

Datetime conversion, numeric conversion and duplicate removal were applied during normalization.

In [9]:
df["ts"] = pd.to_datetime(df["ts"])

numeric_columns = [
    "temperature_2m",
    "relative_humidity_2m",
    "precipitation",
    "wind_speed_10m",
]

for column in numeric_columns:
    df[column] = pd.to_numeric(df[column], errors="coerce")

df = df.drop_duplicates()

Missing values were checked after cleaning and normalization.

In [11]:
df.isna().sum()

ts                      0
temperature_2m          0
relative_humidity_2m    0
precipitation           0
wind_speed_10m          0
city_id                 0
dtype: int64

In [10]:
df.head()

,ts,temperature_2m,relative_humidity_2m,precipitation,wind_speed_10m,city_id
0,2024-05-01 00:00:00,19.6,93,0.0,1.6,JP_TYO
1,2024-05-01 01:00:00,19.9,90,0.0,1.3,JP_TYO
2,2024-05-01 02:00:00,19.2,94,0.0,2.5,JP_TYO
3,2024-05-01 03:00:00,18.9,97,0.0,3.3,JP_TYO
4,2024-05-01 04:00:00,19.1,92,0.0,7.4,JP_TYO